export const projects = [
  {
    title: 'Certificate Generator',
    description: "This simple certificate generator is used to generate pre-template certificates with the user's name. It ease the process of creating certificates for students and teachers.",
      image: 'https://firebasestorage.googleapis.com/v0/b/conquerror-development.appspot.com/o/Arman%2FCertificaateGenerator.jpg?alt=media&token=f537cbd0-2d8d-4ffa-8773-d1705fa12b40',
      tags: ['HTML5', 'JS', 'CSS'],
    source: 'https://github.com/MrSyntax31/certificategenofficial.github.io/tree/master',
    visit: 'https://certificategenerator.netlify.app/',
    id: 0,
  },
  {
    title: 'ConquError',
    description:"ConquError is a community for non-IT and IT enthusiasts to share and learn. ConquError is a learning platform and community that assists students and learners in developing their knowledge and skills in computer programming by providing an alternate manner of comprehending all things IT.",
    image: 'https://firebasestorage.googleapis.com/v0/b/conquerror-development.appspot.com/o/Arman%2FConquError.jpg?alt=media&token=a210aae6-80ff-4893-849c-0442a655ee45',
    tags: ['React', 'JavaScript', 'React-Bootstrap', 'Firebase'],
    source: 'https://github.com/MrSyntax31/theconquerror-app',
    visit: 'https://theconquerror.com/',
    id: 1,
  },
  {
    title: 'Spartan Shoe Shop',
    description: "This is a code repository for simple e-commerce website, it is a web application that allows users to buy shoes and pay for them using credit card.",
      image: 'https://firebasestorage.googleapis.com/v0/b/conquerror-development.appspot.com/o/Arman%2FSpartanShoeshop.jpg?alt=media&token=2d557238-113e-4470-a6f1-b2a4e91e474d',
      tags: ['React', 'Styled-Components'],
    source: 'https://google.com',
    visit: 'https://spartanshoe.netlify.app/',
    id: 2,
  },
  {
    title: 'Mabini Box',
    description: "Mabini Box is a real-time online voting system developed using Node.js and JavaScript. It is a web application that allows users to vote for a candidate and see the results of the vote.",
    image: 'https://firebasestorage.googleapis.com/v0/b/conquerror-development.appspot.com/o/Arman%2FMabiniBox.jpg?alt=media&token=d1facfa2-2d32-4515-8f0c-fc7e6d2d68e1',
    tags: ['HTML5', 'JavaScript', 'NodeJs', 'TSQL'],
    source: 'https://github.com/MrSyntax31/VotingSystem/tree/MrSyntax31-patch-1',
    visit: 'https://mabinibox.netlify.app/',
    id: 3,
  },
  {
    title: 'Mabini Box | 2022',
    description: "Mabini Box is a real-time online voting system developed using Node.js and JavaScript. It is a web application that allows users to vote for a candidate and see the results of the vote.",
    image: 'https://firebasestorage.googleapis.com/v0/b/conquerror-development.appspot.com/o/Homepage%2FAnnotation%202022-09-19%20185055.png?alt=media&token=069f26fa-a0b2-44cf-87d0-30d4f0085e69',
    tags: ['HTML5', 'JavaScript', 'NodeJs', 'Next.JS'],
    source: 'https://github.com/MrSyntax31/CSC-E-Voting-site/tree/main',
    visit: 'https://mabinibox.vercel.app/',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey', },
  { year: 2019, text: 'Worked as volunteer developer in our organization', },
  { year: 2020, text: 'We pioneered the first online voting system in our university.', },
  { year: 2020, text: 'Achieve the Arctic Code Vault Contributor 2020 GitHub Archive Program.', },
  { year: 2021, text: 'Participated in the Research Colloquium', },
  { year: 2021, text: 'Freelance web front-end developer at PilaMoko', },
  { year: 2022, text: 'Jr. Digital Specialist | DTWORDS 24/7 PH', },
];
